
// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;
using Microsoft.ML.Transforms.TimeSeries;
using System;
using System.IO;
using System.Linq;

namespace SentimentModel_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var context = new MLContext();

            Console.WriteLine(Directory.GetCurrentDirectory());
            var data = context.Data.LoadFromTextFile<EURUSDData>("TrainData/eurusd_hour.csv", hasHeader: true, separatorChar: ',');

            var split = context.Data.TrainTestSplit(data, testFraction: 0.5);

            var features = split.TrainSet.Schema.Select(col => col.Name).Where(colName => colName != "BC").ToArray();

            
            var forecastingPipeline = context.Forecasting.ForecastBySsa(
                    "Forecast",
                    nameof(EURUSDData.BC),
                    windowSize: 7,
                    seriesLength: 30,
                    trainSize: 365,
                    horizon: 7                   
                   );

            var model = forecastingPipeline.Fit(data);            

            var forecastingEngine = model.CreateTimeSeriesEngine<EURUSDData, EURUSDForecast>(context);

            var forecasts = forecastingEngine.Predict();

            foreach(var forecast in forecasts.Forecast)
            {
                Console.WriteLine(forecast);
            }

            Console.ReadLine();


            Console.WriteLine("Using model to make single prediction -- Comparing actual BC with predicted BC from sample data...\n\n");


            Console.WriteLine($"Date: {@"2005-05-02"}");
            Console.WriteLine($"Time: {@"00:00"}");
            Console.WriteLine($"BO: {12852F}");
            Console.WriteLine($"BH: {12852F}");
            Console.WriteLine($"BL: {1284F}");
            Console.WriteLine($"BC: {12844F}");
            Console.WriteLine($"BCh: {-8E+15F}");
            Console.WriteLine($"AO: {12854F}");
            Console.WriteLine($"AH: {12854F}");
            Console.WriteLine($"AL: {12842F}");
            Console.WriteLine($"AC: {12846F}");
            Console.WriteLine($"ACh: {-8E+15F}");


            
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
