
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SentimentModel_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SentimentModel.ModelInput sampleData = new SentimentModel.ModelInput()
            {
                Date = @"2005-05-02",
                Time = @"00:00",
                BO = 12852F,
                BH = 12852F,
                BL = 1284F,
                BCh = -8E+15F,
                AO = 12854F,
                AH = 12854F,
                AL = 12842F,
                AC = 12846F,
                ACh = -8E+15F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = SentimentModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual BC with predicted BC from sample data...\n\n");


            Console.WriteLine($"Date: {@"2005-05-02"}");
            Console.WriteLine($"Time: {@"00:00"}");
            Console.WriteLine($"BO: {12852F}");
            Console.WriteLine($"BH: {12852F}");
            Console.WriteLine($"BL: {1284F}");
            Console.WriteLine($"BC: {12844F}");
            Console.WriteLine($"BCh: {-8E+15F}");
            Console.WriteLine($"AO: {12854F}");
            Console.WriteLine($"AH: {12854F}");
            Console.WriteLine($"AL: {12842F}");
            Console.WriteLine($"AC: {12846F}");
            Console.WriteLine($"ACh: {-8E+15F}");


            Console.WriteLine($"\n\nPredicted BC: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
