// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SentimentModel_ConsoleApp1
{
    public partial class SentimentModel
    {
        /// <summary>
        /// model input class for SentimentModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Date")]
            public string Date { get; set; }

            [ColumnName(@"Time")]
            public string Time { get; set; }

            [ColumnName(@"BO")]
            public float BO { get; set; }

            [ColumnName(@"BH")]
            public float BH { get; set; }

            [ColumnName(@"BL")]
            public float BL { get; set; }

            [ColumnName(@"BC")]
            public float BC { get; set; }

            [ColumnName(@"BCh")]
            public float BCh { get; set; }

            [ColumnName(@"AO")]
            public float AO { get; set; }

            [ColumnName(@"AH")]
            public float AH { get; set; }

            [ColumnName(@"AL")]
            public float AL { get; set; }

            [ColumnName(@"AC")]
            public float AC { get; set; }

            [ColumnName(@"ACh")]
            public float ACh { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SentimentModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SentimentModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
